title: "Jay의 프로젝트 허브"
description: "데일리 브리핑 · 게임 기획 · 게임 에셋"
url: "https://eastsea.monster"
baseurl: ""

collections:
  assets:
    output: false

future: true
timezone: Asia/Seoul

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "assets"
    values:
      layout: "asset"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:categories/:year/:month/:day/:title/
